import type { CrossCheckVariable } from "@/lib/types"

const variablesBySlug: Record<string, CrossCheckVariable[]> = {
  "likvidace-vozidla": [
    {
      id: "motor-vin",
      name: "VIN vozidla",
      sourceDocument: "Faktura servisu",
      sourceField: "VIN",
      targetDocument: "Pojistná smlouva HAV",
      targetField: "VIN",
    },
    {
      id: "motor-plate",
      name: "Registrační značka",
      sourceDocument: "Záznam o dopravní nehodě",
      sourceField: "RZ",
      targetDocument: "Pojistná smlouva HAV",
      targetField: "RZ",
    },
    {
      id: "motor-labor",
      name: "Hodiny práce",
      sourceDocument: "Faktura servisu",
      sourceField: "Hodiny",
      targetDocument: "Kalkulace Audatex",
      targetField: "Hodiny",
    },
  ],
  akreditiv: [
    {
      id: "lc-amount",
      name: "Částka faktury",
      sourceDocument: "Obchodní faktura",
      sourceField: "Částka",
      targetDocument: "Text akreditivu",
      targetField: "Částka",
    },
    {
      id: "lc-shipment",
      name: "Datum nalodění",
      sourceDocument: "Náložní list",
      sourceField: "On-board datum",
      targetDocument: "Text akreditivu",
      targetField: "Latest shipment",
    },
    {
      id: "lc-quantity",
      name: "Počet svitků",
      sourceDocument: "Packing list",
      sourceField: "Počet kusů",
      targetDocument: "Text akreditivu",
      targetField: "Množství",
    },
  ],
  "prepravni-skoda-cmr": [
    {
      id: "cmr-seal",
      name: "Číslo plomby",
      sourceDocument: "Fotodokumentace",
      sourceField: "Číslo plomby",
      targetDocument: "Nákladní list CMR",
      targetField: "Číslo plomby",
    },
    {
      id: "cmr-temp",
      name: "Horní teplota",
      sourceDocument: "Teplotní záznam",
      sourceField: "Naměřené maximum",
      targetDocument: "Nákladní list CMR",
      targetField: "Horní mez",
    },
    {
      id: "cmr-pallets",
      name: "Počet palet",
      sourceDocument: "Obchodní faktura",
      sourceField: "Počet kusů",
      targetDocument: "Nákladní list CMR",
      targetField: "Počet kusů",
    },
  ],
  "zajisteni-uveru": [
    {
      id: "col-owner",
      name: "Zástavce",
      sourceDocument: "Zástavní smlouva",
      sourceField: "Zástavce",
      targetDocument: "List vlastnictví",
      targetField: "Vlastník",
    },
    {
      id: "col-parcel",
      name: "Parcela",
      sourceDocument: "Zástavní smlouva",
      sourceField: "Parcela",
      targetDocument: "List vlastnictví",
      targetField: "Parcela",
    },
    {
      id: "col-sum",
      name: "Pojistná částka",
      sourceDocument: "Pojistka nemovitosti",
      sourceField: "Pojistná částka",
      targetDocument: "Odhad",
      targetField: "Hodnota",
    },
  ],
  "karetni-reklamace": [
    {
      id: "card-amount",
      name: "Částka sporu",
      sourceDocument: "Reklamace držitele",
      sourceField: "Částka",
      targetDocument: "Autorizace",
      targetField: "Částka",
    },
    {
      id: "card-merchant",
      name: "Obchodník",
      sourceDocument: "Doklad obchodníka",
      sourceField: "Obchodník",
      targetDocument: "Autorizace",
      targetField: "Obchodník",
    },
    {
      id: "card-address",
      name: "Adresa doručení",
      sourceDocument: "Potvrzení doručení",
      sourceField: "Adresa",
      targetDocument: "Reklamace držitele",
      targetField: "Adresa",
    },
  ],
  "zdravotni-narok": [
    {
      id: "health-patient",
      name: "Pacient",
      sourceDocument: "Faktura poskytovatele",
      sourceField: "Pacient",
      targetDocument: "Průkaz pojištěnce",
      targetField: "Pojištěnec",
    },
    {
      id: "health-code",
      name: "Kód výkonu",
      sourceDocument: "Faktura poskytovatele",
      sourceField: "Kód výkonu",
      targetDocument: "Žádanka nebo recept",
      targetField: "Kód výkonu",
    },
    {
      id: "health-amount",
      name: "Účtovaná částka",
      sourceDocument: "Faktura poskytovatele",
      sourceField: "Částka",
      targetDocument: "Sazebník plátce",
      targetField: "Maximální úhrada",
    },
  ],
  "sla-kredit": [
    {
      id: "sla-start",
      name: "Začátek výpadku",
      sourceDocument: "Trouble ticket",
      sourceField: "Začátek",
      targetDocument: "Záznam monitoringu",
      targetField: "Začátek",
    },
    {
      id: "sla-end",
      name: "Konec výpadku",
      sourceDocument: "Trouble ticket",
      sourceField: "Konec",
      targetDocument: "Záznam monitoringu",
      targetField: "Konec",
    },
    {
      id: "sla-length",
      name: "Délka výpadku",
      sourceDocument: "Trouble ticket",
      sourceField: "Délka",
      targetDocument: "Záznam monitoringu",
      targetField: "Doložený interval",
    },
  ],
  "nahrada-vypadek": [
    {
      id: "out-ean",
      name: "EAN",
      sourceDocument: "Hlášení zákazníka",
      sourceField: "EAN",
      targetDocument: "Provozní deník",
      targetField: "EAN",
    },
    {
      id: "out-start",
      name: "Začátek přerušení",
      sourceDocument: "Hlášení zákazníka",
      sourceField: "Začátek",
      targetDocument: "Provozní deník",
      targetField: "Začátek",
    },
    {
      id: "out-gap",
      name: "Délka mezery",
      sourceDocument: "Data měření",
      sourceField: "Délka mezery",
      targetDocument: "Provozní deník",
      targetField: "Délka přerušení",
    },
  ],
}

export function crossCheckVariablesFor(slug: string) {
  return variablesBySlug[slug]
}
