import type { Scenario } from "@/lib/types"
import { getModule } from "@/lib/modules"

export const scenarios: Scenario[] = [
  {
    slug: "skoda-octavia-hav",
    moduleSlug: "likvidace-vozidla",
    industry: "insurance",
    title: "Havarijní škoda, Škoda Octavia",
    dek: "Servis účtuje zadní nárazník a jiný VIN, než má smlouva. Fotky a protokol policie ukazují jen přední náraz.",
    caller: {
      system: "Salesforce",
      product: "Service Cloud · objekt Claim",
      actor: "Petra Malá",
      actorRole: "likvidátorka HAV",
      recordId: "HAV-2026-18442",
      recordTitle: "Jana Králová · 5A2 1847",
    },
    recordFields: [
      { label: "Pojištěná", value: "Jana Králová" },
      { label: "Smlouva", value: "HAV-448291" },
      { label: "Vozidlo", value: "Škoda Octavia Combi" },
      { label: "RZ / VIN", value: "5A2 1847 · TMBJG7NE5L0123456" },
      { label: "Nehoda", value: "12. 3. 2026, Barrandovský most" },
      { label: "Spoluúčast", value: "5 000 Kč" },
    ],
    documents: [
      {
        id: "doc_policy",
        name: "Pojistná smlouva HAV-448291",
        kind: "Smlouva",
        fields: [
          { label: "VIN", value: "TMBJG7NE5L0123456" },
          { label: "RZ", value: "5A2 1847" },
          { label: "Pojistná doba", value: "1. 1. 2025 – 31. 12. 2026" },
          { label: "Spoluúčast", value: "5 000 Kč" },
        ],
      },
      {
        id: "doc_fnol",
        name: "Hlášení škody",
        kind: "Hlášení",
        fields: [
          { label: "Datum", value: "12. 3. 2026, 18:40" },
          { label: "Místo", value: "Barrandovský most, Praha" },
          { label: "Popis", value: "Náraz do přede mnou jedoucího vozu, přední část" },
          { label: "RZ", value: "5A2 1847" },
        ],
      },
      {
        id: "doc_police",
        name: "Záznam PČR KRPA-88211/PNO-2026",
        kind: "Protokol",
        fields: [
          { label: "Rozsah", value: "Přední nárazník, kapota, levý světlomet" },
          { label: "Zadní část", value: "Bez poškození" },
          { label: "RZ", value: "5A2 1847" },
          { label: "Protistrana", value: "Známá" },
        ],
      },
      {
        id: "doc_photos",
        name: "Fotodokumentace, 14 snímků",
        kind: "Fotky",
        fields: [
          { label: "Poškození", value: "Přední nárazník, kapota, levý světlomet" },
          { label: "Zadní nárazník", value: "Na snímcích bez poškození" },
          { label: "VIN na štítku", value: "TMBJG7NE5L0123456" },
          { label: "RZ", value: "5A2 1847" },
        ],
      },
      {
        id: "doc_invoice",
        name: "Faktura AutoServis Modřany FV-2026-0931",
        kind: "Faktura",
        fields: [
          { label: "VIN", value: "TMBJG7NE5L0123458", conflict: true },
          { label: "Přední díly", value: "48 450 Kč" },
          { label: "Lak zadního nárazníku", value: "18 400 Kč", conflict: true },
          { label: "Práce", value: "14 h × 2 400 Kč = 33 600 Kč", conflict: true },
          { label: "Celkem", value: "100 450 Kč" },
          { label: "Datum", value: "18. 3. 2026" },
        ],
      },
      {
        id: "doc_audatex",
        name: "Kalkulace Audatex",
        kind: "Kalkulace",
        fields: [
          { label: "Přední díly", value: "48 450 Kč" },
          { label: "Zadní nárazník", value: "Není v rozsahu" },
          { label: "Práce", value: "11 h × 1 850 Kč = 20 350 Kč" },
          { label: "Celkem", value: "68 800 Kč" },
        ],
      },
    ],
    request: {
      caller: { system: "salesforce", actor: "petra.mala", recordId: "HAV-2026-18442" },
      policy: {
        id: "HAV-448291",
        plate: "5A2 1847",
        vin: "TMBJG7NE5L0123456",
        deductible: { amount: 5000, currency: "CZK" },
      },
      documents: [
        { id: "doc_policy", type: "policy_schedule", filename: "hav-448291.pdf" },
        { id: "doc_fnol", type: "fnol", filename: "hlaseni.pdf" },
        { id: "doc_police", type: "police_report", filename: "krpa-88211.pdf" },
        { id: "doc_photos", type: "damage_photo", filename: "foto-14.zip" },
        { id: "doc_invoice", type: "repair_invoice", filename: "fv-2026-0931.pdf" },
        { id: "doc_audatex", type: "audatex", filename: "audatex-18442.xml" },
      ],
    },
    checks: [
      {
        id: "period",
        label: "Datum nehody leží v pojistné době",
        status: "pass",
        documentIds: ["doc_policy", "doc_fnol"],
        detail: "12. 3. 2026 je mezi 1. 1. 2025 a 31. 12. 2026.",
      },
      {
        id: "plate",
        label: "RZ 5A2 1847 sedí na smlouvě, hlášení, protokolu i fotkách",
        status: "pass",
        documentIds: ["doc_policy", "doc_fnol", "doc_police", "doc_photos"],
        detail: "Jedna registrační značka ve všech čtyřech podkladech.",
      },
      {
        id: "vin",
        label: "VIN na faktuře se liší od smlouvy a od štítku na fotce",
        status: "fail",
        documentIds: ["doc_invoice", "doc_policy", "doc_photos"],
        detail: "Faktura končí 458. Smlouva i štítek končí 456.",
      },
      {
        id: "scope",
        label: "Fotky odpovídají protokolu: jen přední část",
        status: "pass",
        documentIds: ["doc_photos", "doc_police"],
        detail: "Přední nárazník, kapota, levý světlomet. Zadní část bez poškození.",
      },
      {
        id: "rear",
        label: "Faktura účtuje lak zadního nárazníku bez opory",
        status: "fail",
        documentIds: ["doc_invoice", "doc_photos", "doc_police"],
        detail: "Položka 18 400 Kč. Protokol ani fotky zadní poškození nemají.",
      },
      {
        id: "labor",
        label: "Práce na faktuře je nad kalkulací Audatex",
        status: "fail",
        documentIds: ["doc_invoice", "doc_audatex"],
        detail: "Faktura 14 h × 2 400 Kč. Audatex 11 h × 1 850 Kč.",
      },
      {
        id: "invoice-date",
        label: "Faktura je vystavená až po nehodě",
        status: "pass",
        documentIds: ["doc_invoice", "doc_fnol"],
        detail: "18. 3. 2026 je po 12. 3. 2026.",
      },
    ],
    discrepancies: [
      {
        id: "vin",
        severity: "high",
        title: "VIN na faktuře není VIN pojištěného vozu",
        rows: [
          { source: "Faktura FV-2026-0931", value: "TMBJG7NE5L0123458" },
          { source: "Smlouva HAV-448291", value: "TMBJG7NE5L0123456" },
          { source: "Štítek na fotografii", value: "TMBJG7NE5L0123456" },
        ],
        detail: "Liší se poslední číslice. Faktura může patřit k jinému vozu.",
      },
      {
        id: "rear",
        severity: "high",
        title: "Lak zadního nárazníku nemá oporu v prohlídce",
        rows: [
          { source: "Faktura", value: "Lak zadního nárazníku · 18 400 Kč" },
          { source: "Fotky", value: "Zadní část bez poškození" },
          { source: "Záznam PČR", value: "Poškozena jen přední část" },
        ],
        detail: "Položka se do podložené škody nepočítá.",
      },
      {
        id: "labor",
        severity: "medium",
        title: "Hodiny a sazba práce jsou nad Audatex",
        rows: [
          { source: "Faktura", value: "14 h × 2 400 Kč = 33 600 Kč" },
          { source: "Audatex", value: "11 h × 1 850 Kč = 20 350 Kč" },
        ],
        detail: "Rozdíl 13 250 Kč. Přední díly 48 450 Kč sedí v obou podkladech.",
      },
    ],
    response: {
      traceId: "trc_motor_18442",
      module: "claims.motor.reconcile",
      outcome: "discrepant",
      recommendedAction: "investigate",
      discrepancies: [
        {
          code: "vin_mismatch",
          severity: "high",
          documents: ["doc_invoice", "doc_policy", "doc_photos"],
          values: { invoice: "TMBJG7NE5L0123458", policy: "TMBJG7NE5L0123456" },
        },
        {
          code: "part_not_on_photos",
          severity: "high",
          item: "rear_bumper_paint",
          amount: { amount: 18400, currency: "CZK" },
        },
        {
          code: "labor_above_benchmark",
          severity: "medium",
          invoice: { hours: 14, rate: 2400 },
          audatex: { hours: 11, rate: 1850 },
        },
      ],
      result: {
        currency: "CZK",
        claimedAmount: 100450,
        supportedAmount: 68800,
        unsupportedAmount: 31650,
        passedChecks: ["policy_period", "plate_match", "photo_matches_police", "invoice_after_event"],
      },
    },
    writeback: [
      { label: "Stav ClaimSense", value: "Nesoulad podkladů" },
      { label: "Nárokováno", value: "100 450 Kč" },
      { label: "Podloženo", value: "68 800 Kč" },
      { label: "Nepodloženo", value: "31 650 Kč" },
      { label: "Nesoulady", value: "3" },
      {
        label: "Doporučení",
        value: "Došetřit VIN na faktuře a lak zadního nárazníku. Práci srovnat s Audatex. Celou fakturu neproplácet.",
      },
    ],
    error: {
      status: 503,
      code: "agent_unavailable",
      message: "Agent teď neodpověděl. Záznam ve Salesforce se nezměnil.",
      traceId: "trc_motor_18442_err",
    },
  },
  {
    slug: "akreditiv-ocel-linz",
    moduleSlug: "akreditiv",
    industry: "bank",
    title: "Akreditiv na ocelové svitky",
    dek: "Prezentace z Linze je po datu nalodění, míří do Rotterdamu místo Hamburku a faktura je o 400 eur výš.",
    caller: {
      system: "Core banking",
      product: "Trade finance · prezentace dokumentů",
      actor: "Martin Horák",
      actorRole: "specialista trade finance",
      recordId: "LC-CZ-2026-00418",
      recordTitle: "Kovohutě Brno · Stahlwerk Linz",
    },
    recordFields: [
      { label: "Žadatel", value: "Kovohutě Brno a.s." },
      { label: "Beneficient", value: "Stahlwerk Linz GmbH" },
      { label: "Částka", value: "186 000 EUR" },
      { label: "Dodací podmínka", value: "CIF Hamburg" },
      { label: "Latest shipment", value: "28. 2. 2026" },
      { label: "Zboží", value: "40 svitků, cold-rolled steel coils" },
    ],
    documents: [
      {
        id: "doc_lc",
        name: "Akreditiv LC-CZ-2026-00418",
        kind: "Akreditiv",
        fields: [
          { label: "Částka", value: "186 000 EUR" },
          { label: "Zboží", value: "cold-rolled steel coils" },
          { label: "Kusy", value: "40 svitků" },
          { label: "Vykládka", value: "Hamburg" },
          { label: "Latest shipment", value: "28. 2. 2026" },
          { label: "Pojištění", value: "min. 110 % CIF, ICC (A)" },
        ],
      },
      {
        id: "doc_invoice",
        name: "Faktura SWL-88421",
        kind: "Faktura",
        fields: [
          { label: "Částka", value: "186 400 EUR", conflict: true },
          { label: "Popis", value: "CR steel coils" },
          { label: "Kusy", value: "42 svitků", conflict: true },
          { label: "Beneficient", value: "Stahlwerk Linz GmbH" },
        ],
      },
      {
        id: "doc_bl",
        name: "Náložní list HLCUHAM2602841",
        kind: "B/L",
        fields: [
          { label: "On board", value: "2. 3. 2026", conflict: true },
          { label: "Vykládka", value: "Rotterdam", conflict: true },
          { label: "Kusy", value: "40 svitků" },
          { label: "Hmotnost", value: "820 000 kg" },
        ],
      },
      {
        id: "doc_packing",
        name: "Packing list",
        kind: "Packing list",
        fields: [
          { label: "Kusy", value: "42 svitků", conflict: true },
          { label: "Hmotnost", value: "861 000 kg", conflict: true },
          { label: "Popis", value: "CR steel coils" },
        ],
      },
      {
        id: "doc_origin",
        name: "Certifikát původu",
        kind: "Původ",
        fields: [
          { label: "Země", value: "Rakousko" },
          { label: "Vystavitel", value: "Stahlwerk Linz GmbH" },
        ],
      },
      {
        id: "doc_insurance",
        name: "Pojistný certifikát přepravy",
        kind: "Pojištění",
        fields: [
          { label: "Doložka", value: "ICC (B)", conflict: true },
          { label: "Vystaveno", value: "4. 3. 2026", conflict: true },
          { label: "Trasa", value: "Linz – Rotterdam", conflict: true },
          { label: "Krytí", value: "110 % z 186 400 EUR" },
        ],
      },
    ],
    request: {
      caller: { system: "core_banking", actor: "martin.horak", recordId: "LC-CZ-2026-00418" },
      lc: {
        id: "LC-CZ-2026-00418",
        applicant: "Kovohutě Brno a.s.",
        beneficiary: "Stahlwerk Linz GmbH",
        currency: "EUR",
        amount: 186000,
        incoterm: "CIF",
        portOfDischarge: "Hamburg",
        latestShipmentDate: "2026-02-28",
        goods: "cold-rolled steel coils",
        quantity: 40,
        insurance: { minPercentOfCif: 110, clauses: "ICC(A)" },
      },
      documents: [
        { id: "doc_lc", type: "letter_of_credit" },
        { id: "doc_invoice", type: "commercial_invoice", filename: "SWL-88421.pdf" },
        { id: "doc_bl", type: "bill_of_lading", filename: "HLCUHAM2602841.pdf" },
        { id: "doc_packing", type: "packing_list" },
        { id: "doc_origin", type: "certificate_of_origin" },
        { id: "doc_insurance", type: "cargo_insurance" },
      ],
    },
    checks: [
      {
        id: "amount",
        label: "Faktura překračuje částku akreditivu",
        status: "fail",
        documentIds: ["doc_invoice", "doc_lc"],
        detail: "186 400 EUR proti 186 000 EUR.",
      },
      {
        id: "shipment",
        label: "Nalodění je po latest shipment date",
        status: "fail",
        documentIds: ["doc_bl", "doc_lc"],
        detail: "On board 2. 3. 2026, akreditiv dovoluje nejpozději 28. 2. 2026.",
      },
      {
        id: "port",
        label: "Přístav vykládky není Hamburg",
        status: "fail",
        documentIds: ["doc_bl", "doc_lc"],
        detail: "B/L uvádí Rotterdam.",
      },
      {
        id: "qty",
        label: "Počet svitků se rozchází napříč dokumenty",
        status: "fail",
        documentIds: ["doc_invoice", "doc_packing", "doc_lc", "doc_bl"],
        detail: "Faktura a packing list 42. Akreditiv a náložní list 40. Hmotnost 861 t proti 820 t.",
      },
      {
        id: "insurance",
        label: "Pojistka nesplňuje podmínku akreditivu",
        status: "fail",
        documentIds: ["doc_insurance", "doc_lc", "doc_bl"],
        detail: "ICC (B) místo ICC (A), vystaveno až 4. 3., trasa končí v Rotterdamu.",
      },
      {
        id: "origin",
        label: "Certifikát původu sedí na beneficienta",
        status: "pass",
        documentIds: ["doc_origin", "doc_lc"],
        detail: "Rakousko, Stahlwerk Linz GmbH.",
      },
    ],
    discrepancies: [
      {
        id: "amount",
        severity: "high",
        title: "Faktura je o 400 EUR nad akreditivem",
        rows: [
          { source: "Akreditiv", value: "186 000 EUR" },
          { source: "Faktura SWL-88421", value: "186 400 EUR" },
        ],
        detail: "Prezentace je overdrawn.",
      },
      {
        id: "shipment",
        severity: "high",
        title: "Pozdní nalodění",
        rows: [
          { source: "Akreditiv", value: "Latest shipment 28. 2. 2026" },
          { source: "Náložní list", value: "On board 2. 3. 2026" },
        ],
        detail: "Dva dny po posledním dni nalodění.",
      },
      {
        id: "port",
        severity: "high",
        title: "Jiný přístav vykládky",
        rows: [
          { source: "Akreditiv", value: "CIF Hamburg" },
          { source: "Náložní list", value: "Rotterdam" },
          { source: "Pojistka", value: "Linz – Rotterdam" },
        ],
        detail: "Vykládka ani pojistná trasa neodpovídají akreditivu.",
      },
      {
        id: "qty",
        severity: "high",
        title: "42 svitků na faktuře, 40 na akreditivu a B/L",
        rows: [
          { source: "Akreditiv a B/L", value: "40 svitků · B/L 820 000 kg" },
          { source: "Faktura a packing list", value: "42 svitků · 861 000 kg" },
        ],
        detail: "Kusy a hmotnost se musí srovnat, než se platí.",
      },
      {
        id: "insurance",
        severity: "medium",
        title: "Pojištění není podle podmínky",
        rows: [
          { source: "Akreditiv", value: "ICC (A), před naloděním, destinace Hamburg" },
          { source: "Certifikát", value: "ICC (B), vystaven 4. 3. 2026, Rotterdam" },
        ],
        detail: "Procento 110 % sedí, doložka, datum a přístav ne.",
      },
    ],
    response: {
      traceId: "trc_lc_00418",
      module: "trade.lc.examine",
      outcome: "discrepant",
      recommendedAction: "waive_required",
      discrepancies: [
        { code: "overdrawn", severity: "high", invoiceAmount: 186400, lcAmount: 186000, currency: "EUR" },
        { code: "late_shipment", severity: "high", onBoardDate: "2026-03-02", latestShipmentDate: "2026-02-28" },
        { code: "port_mismatch", severity: "high", billOfLading: "Rotterdam", lc: "Hamburg" },
        { code: "quantity_mismatch", severity: "high", invoice: 42, packingList: 42, lc: 40, billOfLading: 40 },
        { code: "insurance_not_as_required", severity: "medium", clauses: "ICC(B)", issuedOn: "2026-03-04", voyage: "Linz-Rotterdam" },
      ],
      result: {
        presentationStatus: "discrepant",
        waiverAdvice: "Do not pay unless the applicant waives the listed discrepancies.",
        passedChecks: ["beneficiary_on_origin"],
      },
    },
    writeback: [
      { label: "Stav prezentace", value: "Diskrepantní" },
      { label: "Faktura", value: "186 400 EUR" },
      { label: "Akreditiv", value: "186 000 EUR" },
      { label: "Diskrepance", value: "5" },
      {
        label: "Doporučení",
        value: "Neplatit. Poslat žadateli seznam diskrepancí a čekat na waiver.",
      },
    ],
    error: {
      status: 503,
      code: "agent_unavailable",
      message: "Agent teď neodpověděl. Prezentace v core bankingu zůstala bez zápisu.",
      traceId: "trc_lc_00418_err",
    },
  },
  {
    slug: "cmr-pharmanord",
    moduleSlug: "prepravni-skoda-cmr",
    industry: "carrier",
    title: "Přepravní škoda, léčiva do Hamburku",
    dek: "Příjemce vytkl dvě zničené palety při předání. Odesílatel chce celých 92 400 eur a plomba na fotce nesedí.",
    caller: {
      system: "TMS",
      product: "Dispečink škod",
      actor: "Tomáš Veselý",
      actorRole: "disponent škod",
      recordId: "CMR-2026-7731",
      recordTitle: "PharmaNord · 12 palet",
    },
    recordFields: [
      { label: "Odesílatel", value: "PharmaNord Distribution s.r.o." },
      { label: "Příjemce", value: "Apotheke Centrum Hamburg" },
      { label: "Zásilka", value: "12 palet · 4 860 kg" },
      { label: "Instrukce", value: "+2 °C až +8 °C" },
      { label: "Plomba na CMR", value: "448291" },
      { label: "Trasa", value: "Brno 2. 3. → Hamburg 4. 3. 2026" },
    ],
    documents: [
      {
        id: "doc_cmr",
        name: "CMR-7731-26",
        kind: "CMR",
        fields: [
          { label: "Kusy", value: "12 palet" },
          { label: "Hmotnost", value: "4 860 kg" },
          { label: "Plomba", value: "448291" },
          { label: "Teplota", value: "+2 °C až +8 °C" },
        ],
      },
      {
        id: "doc_pod",
        name: "Dodací list s výhradou",
        kind: "Předání",
        fields: [
          { label: "Předání", value: "4. 3. 2026, 11:40, Hamburg" },
          { label: "Výhrada", value: "2 palety zdeformované, plomba porušená" },
          { label: "Kdy zapsáno", value: "Při předání" },
          { label: "Kusy", value: "12 palet" },
        ],
      },
      {
        id: "doc_photos",
        name: "Fotografie poškození a plomby",
        kind: "Fotky",
        fields: [
          { label: "Poškození", value: "Roh dvou palet, mechanický tlak" },
          { label: "Plomba na snímku", value: "448219", conflict: true },
          { label: "Ostatní palety", value: "10 palet bez viditelného poškození" },
        ],
      },
      {
        id: "doc_invoice",
        name: "Obchodní faktura zásilky",
        kind: "Faktura",
        fields: [
          { label: "Hodnota", value: "92 400 EUR", conflict: true },
          { label: "Kusy", value: "12 palet" },
          { label: "Hodnota 2 palet", value: "15 400 EUR" },
        ],
      },
      {
        id: "doc_temp",
        name: "Teplotní záznam",
        kind: "Logger",
        fields: [
          { label: "Instrukce", value: "+2 °C až +8 °C" },
          { label: "Exkurze", value: "3. 3., 11:00–14:05, max 11,2 °C", conflict: true },
          { label: "Délka", value: "3 h 05 min nad 8 °C" },
        ],
      },
      {
        id: "doc_survey",
        name: "Zpráva havarijního komisaře",
        kind: "Komisař",
        fields: [
          { label: "Mechanická škoda", value: "2 palety, manipulace" },
          { label: "Teplota", value: "Exkurze zaznamenána, ke zničeným paletám ji nepřiřazuje" },
          { label: "Zbytek", value: "10 palet bez škody" },
        ],
      },
    ],
    request: {
      caller: { system: "tms", actor: "tomas.vesely", recordId: "CMR-2026-7731" },
      sdrToEur: 1.173,
      cmrLimitRule: "8.33 SDR per kg",
      shipment: {
        pieces: 12,
        weightKg: 4860,
        temperatureC: { min: 2, max: 8 },
        seal: "448291",
      },
      documents: [
        { id: "doc_cmr", type: "cmr" },
        { id: "doc_pod", type: "proof_of_delivery" },
        { id: "doc_photos", type: "damage_photo" },
        { id: "doc_invoice", type: "commercial_invoice" },
        { id: "doc_temp", type: "temperature_log" },
        { id: "doc_survey", type: "survey_report" },
      ],
    },
    checks: [
      {
        id: "deadline",
        label: "Výhrada je na dodacím listu z předání",
        status: "pass",
        documentIds: ["doc_pod"],
        detail: "Zjevná škoda vytčená při předání. Lhůta pro pozdější písemnou výhradu se neotevírá.",
      },
      {
        id: "pieces",
        label: "12 palet sedí na CMR, faktuře i dodacím listu",
        status: "pass",
        documentIds: ["doc_cmr", "doc_invoice", "doc_pod"],
        detail: "Počet kusů se nerozchází.",
      },
      {
        id: "seal",
        label: "Číslo plomby na fotce není číslo z CMR",
        status: "fail",
        documentIds: ["doc_photos", "doc_cmr"],
        detail: "CMR 448291, snímek 448219.",
      },
      {
        id: "temp",
        label: "Teplotní záznam překročil instrukci",
        status: "fail",
        documentIds: ["doc_temp", "doc_cmr"],
        detail: "Max 11,2 °C po dobu 3 h 05 min. Instrukce končí na +8 °C.",
      },
      {
        id: "cause",
        label: "Komisař odděluje manipulaci od teploty",
        status: "pass",
        documentIds: ["doc_survey", "doc_temp", "doc_photos"],
        detail: "Zničené palety přiřazuje manipulaci. Teplotu nepoužívá jako příčinu těchto dvou palet.",
      },
      {
        id: "value",
        label: "Nárok zní na celou zásilku, podložené jsou dvě palety",
        status: "fail",
        documentIds: ["doc_invoice", "doc_survey", "doc_photos"],
        detail: "92 400 EUR za 12 palet. Komisař a fotky drží 2 palety, 15 400 EUR.",
      },
      {
        id: "limit",
        label: "Podložená škoda je pod limitem CMR",
        status: "pass",
        documentIds: ["doc_cmr", "doc_invoice"],
        detail: "8,33 SDR/kg × 4 860 kg × 1,173 = 47 487,50 EUR. 15 400 EUR limit neproráží.",
      },
    ],
    discrepancies: [
      {
        id: "seal",
        severity: "high",
        title: "Plomba na fotografii nesedí na CMR",
        rows: [
          { source: "CMR-7731-26", value: "448291" },
          { source: "Fotografie plomby", value: "448219" },
        ],
        detail: "Čísla jsou přehozená. Bez vysvětlení nejde plomba použít jako důkaz neporušenosti.",
      },
      {
        id: "temp",
        severity: "medium",
        title: "Teplotní exkurze se nesmí slít s rozmačkanými paletami",
        rows: [
          { source: "CMR", value: "Instrukce +2 °C až +8 °C" },
          { source: "Logger", value: "3 h 05 min nad 8 °C, max 11,2 °C" },
          { source: "Komisař", value: "2 palety: manipulace, ne teplota" },
        ],
        detail: "Exkurze se eviduje zvlášť. Není to důvod uznat celou zásilku.",
      },
      {
        id: "value",
        severity: "high",
        title: "Nárok je na 12 palet, podklady drží dvě",
        rows: [
          { source: "Faktura / nárok", value: "92 400 EUR · 12 palet" },
          { source: "Komisař a fotky", value: "15 400 EUR · 2 palety" },
          { source: "Limit CMR", value: "47 487,50 EUR" },
        ],
        detail: "K uznání je 15 400 EUR. Limit CMR se při této částce neuplatní.",
      },
    ],
    response: {
      traceId: "trc_cmr_7731",
      module: "cargo.cmr.reconcile",
      outcome: "discrepant",
      recommendedAction: "partial_approve",
      discrepancies: [
        { code: "seal_mismatch", severity: "high", cmr: "448291", photo: "448219" },
        {
          code: "temperature_excursion",
          severity: "medium",
          maxC: 11.2,
          duration: "PT3H5M",
          surveyorAttribution: "handling_not_temperature",
        },
        { code: "claimed_above_supported", severity: "high", claimed: 92400, supported: 15400, currency: "EUR" },
      ],
      result: {
        currency: "EUR",
        claimedAmount: 92400,
        supportedAmount: 15400,
        cmrLimit: { amount: 47487.5, currency: "EUR" },
        liabilityStance: "partial",
        reservationOnTime: true,
        passedChecks: ["reservation_at_delivery", "piece_count", "cause_separated", "under_cmr_limit"],
      },
    },
    writeback: [
      { label: "Stav ClaimSense", value: "Částečně podloženo" },
      { label: "Nárokováno", value: "92 400 EUR" },
      { label: "Podloženo", value: "15 400 EUR" },
      { label: "Limit CMR", value: "47 487,50 EUR" },
      { label: "Nesoulady", value: "3" },
      {
        label: "Doporučení",
        value: "Uznat mechanické poškození 2 palet. Teplotní exkurzi vést zvlášť. Celou zásilku nekrátit ani neproplácet.",
      },
    ],
    error: {
      status: 503,
      code: "agent_unavailable",
      message: "Agent teď neodpověděl. Záznam v TMS se nezměnil.",
      traceId: "trc_cmr_7731_err",
    },
  },
]

export function getScenario(slug: string) {
  return scenarios.find((item) => item.slug === slug)
}

export function scenarioForModule(moduleSlug: string) {
  return scenarios.find((item) => item.moduleSlug === moduleSlug)
}

export function scenarioModule(scenario: Scenario) {
  return getModule(scenario.moduleSlug)
}
